name: Node.js CI

on:
  schedule:
    - cron: '1 0,12 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v3
      - name: Checkout config repository
        uses: actions/checkout@v3
        with:
          repository: ${{ vars.CONFIG_REPO_NAME }}
          token: ${{ secrets.GH_PAT }}
          path: config
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: node index.js deadline