name: Expired Notify (Hour)

on:
  schedule:
    - cron: '0 * * * *'
  push:

jobs:
  notify:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Checkout config repository
        uses: actions/checkout@v3
        with:
          repository: ${{ vars.CONFIG_REPO_NAME }}
          token: ${{ secrets.GH_PAT }}
          path: config
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: npm i
      - run: ls config
      - run: node index.js expired